[[bollard_ffi]]
arch = "x86_64"
git-tree-sha1 = "bdab87d559c9566a24b029c856b288b556cd58f3"
libc = "glibc"
os = "linux"

    [[bollard_ffi.download]]
    sha256 = "bf8485bca092061ea9a11417f5b30cd0cd2cae5a39d7901c669d709c92c5b3fc"
    url = "https://github.com/FelixKahle/Bollard.jl/releases/download/build-670ff3400490df9ecf280b5cecc7cd420103972c/bollard-linux-x64.tar.gz"
[[bollard_ffi]]
arch = "aarch64"
git-tree-sha1 = "a4b9b2c1f776a34087f680b1f5b7283d760508a9"
libc = "glibc"
os = "linux"

    [[bollard_ffi.download]]
    sha256 = "10dd832c78f8314492488d48bb0491db2a0cf766b446aab35bc75e4e318caab0"
    url = "https://github.com/FelixKahle/Bollard.jl/releases/download/build-670ff3400490df9ecf280b5cecc7cd420103972c/bollard-linux-arm64.tar.gz"
[[bollard_ffi]]
arch = "x86_64"
git-tree-sha1 = "e74942137e9edde7d3e3dd1c0a1f9fa2608d6e24"
os = "windows"

    [[bollard_ffi.download]]
    sha256 = "8882875e677d3223100710c32809fc516e2ff16ff62934600e5461f5c71bb682"
    url = "https://github.com/FelixKahle/Bollard.jl/releases/download/build-670ff3400490df9ecf280b5cecc7cd420103972c/bollard-windows-x64.tar.gz"
[[bollard_ffi]]
arch = "aarch64"
git-tree-sha1 = "846e4ba98b0076d734c0dfb050102aabe20541ac"
os = "windows"

    [[bollard_ffi.download]]
    sha256 = "1edd4ea83613300be035a914ff6b7b1528aa0951d2dfdba9665a624762856a3a"
    url = "https://github.com/FelixKahle/Bollard.jl/releases/download/build-670ff3400490df9ecf280b5cecc7cd420103972c/bollard-windows-arm64.tar.gz"
[[bollard_ffi]]
arch = "x86_64"
git-tree-sha1 = "f2bea239b649b57d33f655df394433d75a8abcae"
os = "macos"

    [[bollard_ffi.download]]
    sha256 = "c57d87970987d3439ae33af868a59bd5342b8863c7d6545141c7c31275c4b3f7"
    url = "https://github.com/FelixKahle/Bollard.jl/releases/download/build-670ff3400490df9ecf280b5cecc7cd420103972c/bollard-macos-x64.tar.gz"
[[bollard_ffi]]
arch = "aarch64"
git-tree-sha1 = "70f0cc71a74e3cd808ff5aa231d81182d5024c3b"
os = "macos"

    [[bollard_ffi.download]]
    sha256 = "16c19e5ff3adb51c0b59866fb673aea27b2e70a305f560906c9d41af5ddc9fb9"
    url = "https://github.com/FelixKahle/Bollard.jl/releases/download/build-670ff3400490df9ecf280b5cecc7cd420103972c/bollard-macos-arm64.tar.gz"
